### ISSUE TITLE
The DoH add-on is not installed from the test channel on Firefox 70

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/doh-rollout#153]
[Affected versions]:
- Firefox Release 70.0 (Build ID: 20191016161957)

[Affected Platforms]:
- All Windows

[Prerequisites]:
- The `devtools.chrome.enabled` preference is set to `true`.

[Steps to reproduce]:
1. Open Firefox with the profile from prerequisites.
2. Open the browser console and enter the following command:
```
Components.utils.import("resource://gre/modules/AddonManager.jsm");
AddonManagerPrivate.backgroundUpdateCheck();
``` 
3. Observe the console output.

[Expected result]:
- The `Promise { <state>: "pending" }` event is displayed and the add-on is fetched and installed.

[Actual result]:
- Only the `Promise { <state>: "pending" }` event is displayed and the add-on is not fetched.

[Notes]:
- Attached a screen recording of the issue:
![test_channel_70](https://user-images.githubusercontent.com/40393891/67692808-63c2a280-f9a9-11e9-9a4b-ce5579662aba.gif)

**Comment by mythmon** [comment]
This is a Balrog issue that I'll be fixing.

**Comment by mythmon** [comment]
This should be fixed now.

**Comment by Softvision-PatriciuPop** [comment]
@mythmon  I retested this scenario and the issues is still reproducible. The add-on is not installed on Firefox 70.0 Build 20191016161957 and 71.0b5 Build 20191028110005 using the steps mentioned above.

**Comment by mythmon** [comment]
The add-on is not enabled for the beta channel, so it is expected that it would not be installed on 71.0b5.

For the release version, are you using the Balrog test channel? I failed to mention it in this issue, but this add-on has only been deployed to that channel, not the production one. The STR didn't mention having that as a prerequisite

**Comment by mythmon** [comment]
Thanks for the clarification.

**Comment by mythmon** [comment]
We have found a fixed an issue with the testing channel that was causing this. Maxx was able to install the add-on from the testing channel on Firefox 70. This should be working now, please verify.

**Comment by SoftVision-CarmenFat** [comment]
I have re-tested this issue and the add-on is now installed from the test channel on both Release 69.0.3 and Release 70.
